// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/atreya2011/grpc-practice/basic-crud/basiccrud/basiccrud.proto

package basiccrud

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Fullname struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName           string   `protobuf:"bytes,3,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fullname) Reset()         { *m = Fullname{} }
func (m *Fullname) String() string { return proto.CompactTextString(m) }
func (*Fullname) ProtoMessage()    {}
func (*Fullname) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b11dc62e5c5a7d, []int{0}
}

func (m *Fullname) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fullname.Unmarshal(m, b)
}
func (m *Fullname) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fullname.Marshal(b, m, deterministic)
}
func (m *Fullname) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fullname.Merge(m, src)
}
func (m *Fullname) XXX_Size() int {
	return xxx_messageInfo_Fullname.Size(m)
}
func (m *Fullname) XXX_DiscardUnknown() {
	xxx_messageInfo_Fullname.DiscardUnknown(m)
}

var xxx_messageInfo_Fullname proto.InternalMessageInfo

func (m *Fullname) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Fullname) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Fullname) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Fullname) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type CreateRequest struct {
	Fullname             *Fullname `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b11dc62e5c5a7d, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetFullname() *Fullname {
	if m != nil {
		return m.Fullname
	}
	return nil
}

type CreateResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b11dc62e5c5a7d, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b11dc62e5c5a7d, []int{3}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadResponse struct {
	Fullname             *Fullname `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b11dc62e5c5a7d, []int{4}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetFullname() *Fullname {
	if m != nil {
		return m.Fullname
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b11dc62e5c5a7d, []int{5}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Fullnames            []*Fullname `protobuf:"bytes,1,rep,name=fullnames,proto3" json:"fullnames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58b11dc62e5c5a7d, []int{6}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetFullnames() []*Fullname {
	if m != nil {
		return m.Fullnames
	}
	return nil
}

func init() {
	proto.RegisterType((*Fullname)(nil), "basiccrud.Fullname")
	proto.RegisterType((*CreateRequest)(nil), "basiccrud.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "basiccrud.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "basiccrud.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "basiccrud.ReadResponse")
	proto.RegisterType((*ListRequest)(nil), "basiccrud.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "basiccrud.ListResponse")
}

func init() {
	proto.RegisterFile("github.com/atreya2011/grpc-practice/basic-crud/basiccrud/basiccrud.proto", fileDescriptor_58b11dc62e5c5a7d)
}

var fileDescriptor_58b11dc62e5c5a7d = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x8e, 0xd4, 0x30,
	0x10, 0xc6, 0x95, 0xdc, 0x72, 0xda, 0x4c, 0x6e, 0x4f, 0xc2, 0x87, 0x20, 0x17, 0x38, 0x11, 0xb9,
	0x3a, 0x21, 0xdd, 0x9a, 0x2c, 0x1d, 0x0d, 0x7f, 0x4e, 0x42, 0x14, 0x88, 0x22, 0x14, 0x94, 0xc8,
	0x1b, 0x7b, 0x23, 0x4b, 0xde, 0x38, 0xd8, 0x0e, 0x08, 0x21, 0x1a, 0x7a, 0x2a, 0x1e, 0x8d, 0x57,
	0xe0, 0x41, 0x50, 0xec, 0x64, 0x37, 0x61, 0xa1, 0xb8, 0xce, 0x9e, 0xef, 0x9b, 0x9f, 0xbf, 0x19,
	0x19, 0x5e, 0x57, 0xc2, 0x4a, 0xba, 0x5e, 0x96, 0x6a, 0x4b, 0xa8, 0xd5, 0xfc, 0x0b, 0x5d, 0x3d,
	0xce, 0x73, 0x52, 0xe9, 0xa6, 0xbc, 0x6a, 0x34, 0x2d, 0xad, 0x28, 0x39, 0x59, 0x53, 0x23, 0xca,
	0xab, 0x52, 0xb7, 0xcc, 0x1f, 0xa7, 0xa7, 0x65, 0xa3, 0x95, 0x55, 0x28, 0xda, 0x15, 0xd2, 0x07,
	0x95, 0x52, 0x95, 0xe4, 0x84, 0x36, 0x82, 0xd0, 0xba, 0x56, 0x96, 0x5a, 0xa1, 0x6a, 0xe3, 0x8d,
	0xf8, 0x33, 0xcc, 0x5f, 0xb5, 0x52, 0xd6, 0x74, 0xcb, 0xd1, 0x29, 0x84, 0x82, 0x25, 0x41, 0x16,
	0x5c, 0xde, 0x2a, 0x42, 0xc1, 0xd0, 0x05, 0xc0, 0x46, 0x68, 0x63, 0x3f, 0x74, 0x6a, 0x12, 0x66,
	0xc1, 0x65, 0x54, 0x44, 0xae, 0xf2, 0xb6, 0xb3, 0x3f, 0x84, 0x78, 0x2b, 0x18, 0x93, 0xdc, 0xeb,
	0x47, 0x4e, 0x07, 0x5f, 0x72, 0x86, 0xfb, 0x10, 0x49, 0x3a, 0xb4, 0xcf, 0x9c, 0x3c, 0xef, 0x0a,
	0x9d, 0x88, 0x9f, 0xc3, 0xe2, 0x5a, 0x73, 0x6a, 0x79, 0xc1, 0x3f, 0xb6, 0xdc, 0x58, 0x44, 0x60,
	0xbe, 0xe9, 0x93, 0xb8, 0x0c, 0xf1, 0xea, 0x6c, 0xb9, 0x1f, 0x6b, 0x08, 0x59, 0xec, 0x4c, 0x38,
	0x83, 0xd3, 0x81, 0x60, 0x1a, 0x55, 0x9b, 0x83, 0x01, 0xf0, 0x05, 0xc4, 0x05, 0xa7, 0x6c, 0x78,
	0xe1, 0x6f, 0xf9, 0x19, 0x9c, 0x78, 0xb9, 0x6f, 0xbf, 0x71, 0x82, 0x05, 0xc4, 0x6f, 0x84, 0xb1,
	0x3d, 0x1f, 0xbf, 0x80, 0x13, 0x7f, 0xed, 0x79, 0x39, 0x44, 0x83, 0xd5, 0x24, 0x41, 0x76, 0xf4,
	0x3f, 0xe0, 0xde, 0xb5, 0xfa, 0x11, 0x42, 0xf4, 0xb2, 0x73, 0x5c, 0xeb, 0x96, 0xa1, 0xf7, 0x70,
	0xec, 0x27, 0x44, 0xc9, 0xa8, 0x6f, 0xb2, 0xb6, 0xf4, 0xfc, 0x1f, 0x8a, 0x7f, 0x1f, 0x27, 0xdf,
	0x7f, 0xfd, 0xfe, 0x19, 0x22, 0xbc, 0x20, 0x9f, 0xf2, 0xfd, 0x0f, 0x79, 0x1a, 0x3c, 0x42, 0x05,
	0xcc, 0xba, 0xa4, 0xe8, 0xee, 0xa8, 0x79, 0x34, 0x49, 0x7a, 0xef, 0xa0, 0xde, 0x23, 0xcf, 0x1d,
	0xf2, 0x0c, 0xdd, 0x9e, 0x20, 0x09, 0x95, 0x12, 0xbd, 0x83, 0x59, 0xb7, 0xcd, 0x09, 0x73, 0xb4,
	0xfd, 0x09, 0x73, 0xbc, 0x76, 0x9c, 0x3a, 0xe6, 0x1d, 0x84, 0xa6, 0xcc, 0xaf, 0x82, 0x7d, 0x5b,
	0x1f, 0xbb, 0x5f, 0xfa, 0xe4, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0x3a, 0x8f, 0xff, 0x1a,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BasicCrudClient is the client API for BasicCrud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BasicCrudClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type basicCrudClient struct {
	cc *grpc.ClientConn
}

func NewBasicCrudClient(cc *grpc.ClientConn) BasicCrudClient {
	return &basicCrudClient{cc}
}

func (c *basicCrudClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/basiccrud.BasicCrud/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basicCrudClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/basiccrud.BasicCrud/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basicCrudClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/basiccrud.BasicCrud/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasicCrudServer is the server API for BasicCrud service.
type BasicCrudServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
}

func RegisterBasicCrudServer(s *grpc.Server, srv BasicCrudServer) {
	s.RegisterService(&_BasicCrud_serviceDesc, srv)
}

func _BasicCrud_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasicCrudServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basiccrud.BasicCrud/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasicCrudServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasicCrud_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasicCrudServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basiccrud.BasicCrud/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasicCrudServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasicCrud_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasicCrudServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basiccrud.BasicCrud/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasicCrudServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BasicCrud_serviceDesc = grpc.ServiceDesc{
	ServiceName: "basiccrud.BasicCrud",
	HandlerType: (*BasicCrudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BasicCrud_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _BasicCrud_List_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _BasicCrud_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/atreya2011/grpc-practice/basic-crud/basiccrud/basiccrud.proto",
}
